from flask import Flask, render_template, request, redirect, url_for, session, send_file
import tensorflow as tf
from PIL import Image
import numpy as np
import os
from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from datetime import datetime

app = Flask(__name__)
app.secret_key = 'your_secret_key'  # Change this to a secure secret key

# Load the ML model
model = tf.keras.models.load_model('blood_group_cnn_model_v2.h5')

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/start')
def start():
    return render_template('ready.html')

@app.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        # Add your authentication logic here
        session['logged_in'] = True
        session['username'] = username  # Store username in session
        return redirect(url_for('upload'))
    return render_template('login.html')

def generate_result_pdf(username, blood_group):
    buffer = BytesIO()
    p = canvas.Canvas(buffer, pagesize=letter)
    
    # Add header with logo/title
    p.setFont("Helvetica-Bold", 24)
    p.drawString(200, 750, "Medical Laboratory Report")
    
    # Add laboratory information
    p.setFont("Helvetica-Bold", 12)
    p.drawString(50, 700, "BLOOD GROUP ANALYSIS REPORT")
    p.line(50, 695, 550, 695)  # Horizontal line
    
    # Add patient information section
    p.setFont("Helvetica-Bold", 12)
    p.drawString(50, 660, "Patient Information:")
    p.setFont("Helvetica", 11)
    p.drawString(70, 640, f"Patient Name: {username}")
    p.drawString(70, 620, f"Report Date: {datetime.now().strftime('%d-%m-%Y')}")
    p.drawString(70, 600, f"Report Time: {datetime.now().strftime('%H:%M:%S')}")
    p.drawString(350, 640, "Report ID: " + datetime.now().strftime('%Y%m%d%H%M'))
    
    # Add test results section
    p.setFont("Helvetica-Bold", 12)
    p.drawString(50, 560, "Test Results:")
    p.line(50, 555, 550, 555)
    
    # Create table headers
    p.setFont("Helvetica-Bold", 11)
    p.drawString(70, 535, "Test Parameter")
    p.drawString(250, 535, "Result")
    p.drawString(400, 535, "Reference Method")
    
    # Add test details
    p.setFont("Helvetica", 11)
    p.drawString(70, 515, "Blood Group")
    p.drawString(250, 515, blood_group)
    p.drawString(400, 515, "Fingerprint Analysis (AI)")
    
    # Add interpretation
    p.setFont("Helvetica-Bold", 12)
    p.drawString(50, 465, "Interpretation:")
    p.setFont("Helvetica", 11)
    p.drawString(70, 445, f"The patient's blood group is determined to be {blood_group} based on")
    p.drawString(70, 430, "fingerprint pattern analysis using artificial intelligence.")
    
    # Add notes section
    p.setFont("Helvetica-Bold", 12)
    p.drawString(50, 380, "Notes:")
    p.setFont("Helvetica", 10)
    p.drawString(70, 360, "1. This is an AI-assisted preliminary analysis.")
    p.drawString(70, 345, "2. Results should be confirmed with standard blood testing methods.")
    p.drawString(70, 330, "3. This report is generated automatically and is valid without signature.")
    
    # Add footer
    p.line(50, 100, 550, 100)
    p.setFont("Helvetica", 9)
    p.drawString(50, 80, "Generated by: Blood Group Analysis System")
    p.drawString(50, 65, f"Report Generated on: {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}")
    p.drawString(400, 80, "Page 1 of 1")
    
    p.showPage()
    p.save()
    buffer.seek(0)
    return buffer

@app.route('/upload', methods=['GET', 'POST'])
def upload():
    if not session.get('logged_in'):
        return redirect(url_for('login'))
    
    if request.method == 'POST':
        if 'file' not in request.files:
            return redirect(request.url)
        file = request.files['file']
        if file.filename == '':
            return redirect(request.url)
        
        if file:
            # Process the image
            img = Image.open(file)
            # Convert to grayscale
            img = img.convert('L')
            img = img.resize((128,128))
            img_array = np.array(img)
            img_array = np.expand_dims(img_array, axis=-1)
            img_array = np.expand_dims(img_array, axis=0)
            img_array = img_array.astype('float32') / 255.0
            
            # Make prediction
            prediction = model.predict(img_array)
            blood_group = np.argmax(prediction[0])
            blood_groups = ['A+', 'A-', 'AB+', 'AB-', 'B+', 'B-', 'O+', 'O-']
            result = blood_groups[blood_group]
            
            # Generate PDF with username in filename
            username = session.get('username', 'User')
            pdf_buffer = generate_result_pdf(username, result)
            
            # Create filename with username and date
            filename = f"{username}_blood_group_report_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf"
            
            return send_file(
                pdf_buffer,
                as_attachment=True,
                download_name=filename,
                mimetype='application/pdf'
            )
    
    return render_template('upload.html')
    

if __name__ == '__main__':
    app.run(debug=True)